# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1dcf96055896930fa36ebd1afefd1f0bfae11601ec0d78a45bf677c2ea85828c27601c6b78d26f767d2a368188471cbc05f8e35155cb91e056423205853c54bc

test:
  secret_key_base: 0dca4528dd3a5e9965e21b0f2fb6b544fe673b35b91ad8526f139fdab31127a3325648c9db03d106444ac3247d86d3caeed61b769972802640b66c5393f5bb9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
